```{r required functions & pkgs}
################################################################################################################################################################################################
################################################################### Load required packages & create .na functions}##############################################################################
################################################################################################################################################################################################

rm(list = ls())

requiredpackages <- c("berryFunctions", "dplyr", "lubridate", "ggsci", "insight", "pivottabler", "purrr", "readxl", "openxlsx", "tidyr", "XML", "xml2")

install_load <- function(packages) {
  for (p in packages) {
    if (!p %in% rownames(installed.packages())) {
      install.packages(p)
    }
    library(p,character.only = TRUE)
  }
}

suppressMessages(install_load(requiredpackages))
suppressMessages(rm(requiredpackages, install_load))

PTunit <- "PT_500057"
MMtype <- "NIE"
MMtype2 <- "NI"

# Add cbind.na, rbind.na, data.frame.na functions}
cbind.na <- function (..., deparse.level = 1)
{
  na <- nargs() - (!missing(deparse.level))
  deparse.level <- as.integer(deparse.level)
  stopifnot(0 <= deparse.level, deparse.level <= 2)
  argl <- list(...)
  while (na > 0 && is.null(argl[[na]])) {
    argl <- argl[-na]
    na <- na - 1
  }
  if (na == 0)
    return(NULL)
  if (na == 1) {
    if (isS4(..1))
      return(cbind2(..1))
    else return(matrix(...)) ##.Internal(cbind(deparse.level, ...)))
  }
  if (deparse.level) {
    symarg <- as.list(sys.call()[-1L])[1L:na]
    Nms <- function(i) {
      if (is.null(r <- names(symarg[i])) || r == "") {
        if (is.symbol(r <- symarg[[i]]) || deparse.level ==
            2)
          deparse(r)
      }
      else r
    }
  }
  ## deactivated, otherwise no fill in with two arguments
  if (na == 0) {
    r <- argl[[2]]
    fix.na <- FALSE
  }
  else {
    nrs <- unname(lapply(argl, nrow))
    iV <- sapply(nrs, is.null)
    fix.na <- identical(nrs[(na - 1):na], list(NULL, NULL))
    ## deactivated, otherwise data will be recycled
    #if (fix.na) {
    # nr <- max(if (all(iV)) sapply(argl, length) else unlist(nrs[!iV]))
    # argl[[na]] <- cbind(rep(argl[[na]], length.out = nr),
    # deparse.level = 0)
    #}
    if (deparse.level) {
      if (fix.na)
        fix.na <- !is.null(Nna <- Nms(na))
      if (!is.null(nmi <- names(argl)))
        iV <- iV & (nmi == "")
      ii <- if (fix.na)
        2:(na - 1)
      else 2:na
      if (any(iV[ii])) {
        for (i in ii[iV[ii]]) if (!is.null(nmi <- Nms(i)))
          names(argl)[i] <- nmi
      }
    }
    
    ## filling with NA's to maximum occuring nrows
    nRow <- as.numeric(sapply(argl, function(x) NROW(x)))
    maxRow <- max(nRow, na.rm = TRUE)
    argl <- lapply(argl, function(x) if (is.null(nrow(x))) c(x, rep(NA, maxRow - length(x)))
                   else rbind.na(x, matrix(, maxRow - nrow(x), ncol(x))))
    r <- do.call(cbind, c(argl[-1L], list(deparse.level = deparse.level)))
  }
  d2 <- dim(r)
  r <- cbind2(argl[[1]], r)
  if (deparse.level == 0)
    return(r)
  ism1 <- !is.null(d1 <- dim(..1)) && length(d1) == 2L
  ism2 <- !is.null(d2) && length(d2) == 2L && !fix.na
  if (ism1 && ism2)
    return(r)
  Ncol <- function(x) {
    d <- dim(x)
    if (length(d) == 2L)
      d[2L]
    else as.integer(length(x) > 0L)
  }
  nn1 <- !is.null(N1 <- if ((l1 <- Ncol(..1)) && !ism1) Nms(1))
  nn2 <- !is.null(N2 <- if (na == 2 && Ncol(..2) && !ism2) Nms(2))
  if (nn1 || nn2 || fix.na) {
    if (is.null(colnames(r)))
      colnames(r) <- rep.int("", ncol(r))
    setN <- function(i, nams) colnames(r)[i] <<- if (is.null(nams))
      ""
    else nams
    if (nn1)
      setN(1, N1)
    if (nn2)
      setN(1 + l1, N2)
    if (fix.na)
      setN(ncol(r), Nna)
  }
  r
}

rbind.na <- function (..., deparse.level = 1)
{
  na <- nargs() - (!missing(deparse.level))
  deparse.level <- as.integer(deparse.level)
  stopifnot(0 <= deparse.level, deparse.level <= 2)
  argl <- list(...)
  while (na > 0 && is.null(argl[[na]])) {
    argl <- argl[-na]
    na <- na - 1
  }
  if (na == 0)
    return(NULL)
  if (na == 1) {
    if (isS4(..1))
      return(rbind2(..1))
    else return(matrix(..., nrow = 1)) ##.Internal(rbind(deparse.level, ...)))
  }
  if (deparse.level) {
    symarg <- as.list(sys.call()[-1L])[1L:na]
    Nms <- function(i) {
      if (is.null(r <- names(symarg[i])) || r == "") {
        if (is.symbol(r <- symarg[[i]]) || deparse.level ==
            2)
          deparse(r)
      }
      else r
    }
  }
  
  ## deactivated, otherwise no fill in with two arguments
  if (na == 0) {
    r <- argl[[2]]
    fix.na <- FALSE
  }
  else {
    nrs <- unname(lapply(argl, ncol))
    iV <- sapply(nrs, is.null)
    fix.na <- identical(nrs[(na - 1):na], list(NULL, NULL))
    ## deactivated, otherwise data will be recycled
    #if (fix.na) {
    #    nr <- max(if (all(iV)) sapply(argl, length) else unlist(nrs[!iV]))
    #    argl[[na]] <- rbind(rep(argl[[na]], length.out = nr),
    #        deparse.level = 0)
    #}
    if (deparse.level) {
      if (fix.na)
        fix.na <- !is.null(Nna <- Nms(na))
      if (!is.null(nmi <- names(argl)))
        iV <- iV & (nmi == "")
      ii <- if (fix.na)
        2:(na - 1)
      else 2:na
      if (any(iV[ii])) {
        for (i in ii[iV[ii]]) if (!is.null(nmi <- Nms(i)))
          names(argl)[i] <- nmi
      }
    }
    
    ## filling with NA's to maximum occuring ncols
    nCol <- as.numeric(sapply(argl, function(x) if (is.null(ncol(x))) length(x)
                              else ncol(x)))
    maxCol <- max(nCol, na.rm = TRUE)
    argl <- lapply(argl, function(x)  if (is.null(ncol(x))) c(x, rep(NA, maxCol - length(x)))
                   else cbind(x, matrix(, nrow(x), maxCol - ncol(x))))
    
    ## create a common name vector from the
    ## column names of all 'argl' items
    namesVEC <- rep(NA, maxCol)
    for (i in 1:length(argl)) {
      CN <- colnames(argl[[i]])
      m <- !(CN %in% namesVEC)
      namesVEC[m] <- CN[m]
    }
    
    ## make all column names from common 'namesVEC'
    for (j in 1:length(argl)) {
      if (!is.null(ncol(argl[[j]]))) colnames(argl[[j]]) <- namesVEC
    }
    
    r <- do.call(rbind, c(argl[-1L], list(deparse.level = deparse.level)))
  }
  
  d2 <- dim(r)
  
  ## make all column names from common 'namesVEC'
  colnames(r) <- colnames(argl[[1]])
  
  r <- rbind2(argl[[1]], r)
  
  if (deparse.level == 0)
    return(r)
  ism1 <- !is.null(d1 <- dim(..1)) && length(d1) == 2L
  ism2 <- !is.null(d2) && length(d2) == 2L && !fix.na
  if (ism1 && ism2)
    return(r)
  Nrow <- function(x) {
    d <- dim(x)
    if (length(d) == 2L)
      d[1L]
    else as.integer(length(x) > 0L)
  }
  nn1 <- !is.null(N1 <- if ((l1 <- Nrow(..1)) && !ism1) Nms(1))
  nn2 <- !is.null(N2 <- if (na == 2 && Nrow(..2) && !ism2) Nms(2))
  if (nn1 || nn2 || fix.na) {
    if (is.null(rownames(r)))
      rownames(r) <- rep.int("", nrow(r))
    setN <- function(i, nams) rownames(r)[i] <<- if (is.null(nams))
      ""
    else nams
    if (nn1)
      setN(1, N1)
    if (nn2)
      setN(1 + l1, N2)
    if (fix.na)
      setN(nrow(r), Nna)
  }
  r
}


data.frame.na <- function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,
                           stringsAsFactors = FALSE)
{
  data.row.names <- if (check.rows && is.null(row.names))
    function(current, new, i) {
      if (is.character(current))
        new <- as.character(new)
      if (is.character(new))
        current <- as.character(current)
      if (anyDuplicated(new))
        return(current)
      if (is.null(current))
        return(new)
      if (all(current == new) || all(current == ""))
        return(new)
      stop(gettextf("mismatch of row names in arguments of 'data.frame', item %d",
                    i), domain = NA)
    }
  else function(current, new, i) {
    if (is.null(current)) {
      if (anyDuplicated(new)) {
        warning("some row.names duplicated: ", paste(which(duplicated(new)),
                                                     collapse = ","), " --> row.names NOT used")
        current
      }
      else new
    }
    else current
  }
  object <- as.list(substitute(list(...)))[-1L]
  mrn <- is.null(row.names)
  x <- list(...)
  n <- length(x)
  if (n < 1L) {
    if (!mrn) {
      if (is.object(row.names) || !is.integer(row.names))
        row.names <- as.character(row.names)
      if (any(is.na(row.names)))
        stop("row names contain missing values")
      if (anyDuplicated(row.names))
        stop("duplicate row.names: ", paste(unique(row.names[duplicated(row.names)]),
                                            collapse = ", "))
    }
    else row.names <- integer(0L)
    return(structure(list(), names = character(0L), row.names = row.names,
                     class = "data.frame"))
  }
  vnames <- names(x)
  if (length(vnames) != n)
    vnames <- character(n)
  no.vn <- !nzchar(vnames)
  vlist <- vnames <- as.list(vnames)
  nrows <- ncols <- integer(n)
  for (i in seq_len(n)) {
    xi <- if (is.character(x[[i]]) || is.list(x[[i]]))
      as.data.frame(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors)
    else as.data.frame(x[[i]], optional = TRUE)
    nrows[i] <- .row_names_info(xi)
    ncols[i] <- length(xi)
    namesi <- names(xi)
    if (ncols[i] > 1L) {
      if (length(namesi) == 0L)
        namesi <- seq_len(ncols[i])
      if (no.vn[i])
        vnames[[i]] <- namesi
      else vnames[[i]] <- paste(vnames[[i]], namesi, sep = ".")
    }
    else {
      if (length(namesi))
        vnames[[i]] <- namesi
      else if (no.vn[[i]]) {
        tmpname <- deparse(object[[i]])[1L]
        if (substr(tmpname, 1L, 2L) == "I(") {
          ntmpn <- nchar(tmpname, "c")
          if (substr(tmpname, ntmpn, ntmpn) == ")")
            tmpname <- substr(tmpname, 3L, ntmpn - 1L)
        }
        vnames[[i]] <- tmpname
      }
    }
    if (missing(row.names) && nrows[i] > 0L) {
      rowsi <- attr(xi, "row.names")
      nc <- nchar(rowsi, allowNA = FALSE)
      nc <- nc[!is.na(nc)]
      if (length(nc) && any(nc))
        row.names <- data.row.names(row.names, rowsi,
                                    i)
    }
    nrows[i] <- abs(nrows[i])
    vlist[[i]] <- xi
  }
  nr <- max(nrows)
  for (i in seq_len(n)[nrows < nr]) {
    xi <- vlist[[i]]
    if (nrows[i] > 0L) {
      xi <- unclass(xi)
      fixed <- TRUE
      for (j in seq_along(xi)) {
        ### added NA fill to max length/nrow
        xi1 <- xi[[j]]
        if (is.vector(xi1) || is.factor(xi1))
          xi[[j]] <- c(xi1, rep(NA, nr - nrows[i]))
        else if (is.character(xi1) && class(xi1) == "AsIs")
          xi[[j]] <- structure(c(xi1, rep(NA, nr - nrows[i])),
                               class = class(xi1))
        else if (inherits(xi1, "Date") || inherits(xi1,
                                                   "POSIXct"))
          xi[[j]] <- c(xi1, rep(NA, nr - nrows[i]))
        else {
          fixed <- FALSE
          break
        }
      }
      if (fixed) {
        vlist[[i]] <- xi
        next
      }
    }
    stop("arguments imply differing number of rows: ", paste(unique(nrows),
                                                             collapse = ", "))
  }
  value <- unlist(vlist, recursive = FALSE, use.names = FALSE)
  vnames <- unlist(vnames[ncols > 0L])
  noname <- !nzchar(vnames)
  if (any(noname))
    vnames[noname] <- paste("Var", seq_along(vnames), sep = ".")[noname]
  if (check.names)
    vnames <- make.names(vnames, unique = TRUE)
  names(value) <- vnames
  if (!mrn) {
    if (length(row.names) == 1L && nr != 1L) {
      if (is.character(row.names))
        row.names <- match(row.names, vnames, 0L)
      if (length(row.names) != 1L || row.names < 1L ||
          row.names > length(vnames))
        stop("row.names should specify one of the variables")
      i <- row.names
      row.names <- value[[i]]
      value <- value[-i]
    }
    else if (!is.null(row.names) && length(row.names) !=
             nr)
      stop("row names supplied are of the wrong length")
  }
  else if (!is.null(row.names) && length(row.names) != nr) {
    warning("row names were found from a short variable and have been discarded")
    row.names <- NULL
  }
  if (is.null(row.names))
    row.names <- .set_row_names(nr)
  else {
    if (is.object(row.names) || !is.integer(row.names))
      row.names <- as.character(row.names)
    if (any(is.na(row.names)))
      stop("row names contain missing values")
    if (anyDuplicated(row.names))
      stop("duplicate row.names: ", paste(unique(row.names[duplicated(row.names)]),
                                          collapse = ", "))
  }
  attr(value, "row.names") <- row.names
  attr(value, "class") <- "data.frame"
  value
}
```

```{r Setup}

# USERNAME & DRIVES
un <- Sys.getenv("USERNAME")
if (un == "kathy.callan") {
  accdrive <- "X"
  edrive <- "Y"
  e2drive <- "Z"
} else if (un == "emma.mullan") {
  accdrive <- "X"
  edrive <- "Z"
  e2drive <- "Y"
} else {
  stop("Unexpected user. Stopping...")
}

initials <- strsplit(un, "\\.")
initials <- sapply(initials, function(x) substr(x, 1, 1))
initials <- toupper(paste(initials[, 1], collapse = ""))

# *Styles*
negStyle <- createStyle(fontColour = "#9C0006", bgFill = "#FFC7CE")
posStyle <- createStyle(fontColour = "#006100", bgFill = "#C6EFCE")
boldStyle <- createStyle(textDecoration = "bold")
yellowStyle <- createStyle(fontColour = 'red', textDecoration = 'bold', fgFill = 'yellow', border = "TopBottomLeftRight")
orangeStyle <- createStyle(numFmt = "[$£]#,##0.00", fgFill = '#FFCC99', border = "TopBottomLeftRight")
whiteStyle <- createStyle(numFmt = "[$£]#,##0.00", border = "TopBottomLeftRight")
sterling <- createStyle(numFmt = "[$£]#,##0.00")
DATE <- createStyle(numFmt = "DATE")
NUMBER <- createStyle(numFmt = "NUMBER")
TIME <- createStyle(numFmt = "hh:mm:ss")
PERCENT <- createStyle(numFmt = "0%")
redStyle <- createStyle(fontColour = 'red', textDecoration = 'bold')
bluestyle <- createStyle(fgFill = "#B4C6E7")
thicktop <- createStyle(border = 'Top', borderStyle = 'thick')
thickbottom <- createStyle(border = 'Bottom', borderStyle = 'thick')
thickleft <- createStyle(border = 'Left', borderStyle = 'thick')
thickright <- createStyle(border = 'Right', borderStyle = 'thick')
thicktl <- createStyle(border = 'TopLeft', borderStyle = 'thick')
thicktr <- createStyle(border = 'TopRight', borderStyle = 'thick')
thickbl <- createStyle(border = 'BottomLeft', borderStyle = 'thick')
thickbr <- createStyle(border = 'BottomRight', borderStyle = 'thick')
```

```{r}

receiveddate <- readline(prompt = "Enter the DATE the document was RECEIVED in the format YYYYMMDD: ")

# DOCUMENT

# read in XML file
xmlfile <- list.files(paste0(accdrive, ":/GeneralAccounts/Settlement/ISEM Settlement/", PTunit, "/MO/Document/"), full.names = TRUE)
xmlfile <- xmlfile[grepl(x = xmlfile, pattern = receiveddate)]
if (length(xmlfile) != 1) {
  stop("Please check ISEM Settlement folder for document before rerunning. Stopping...")
}

# Get invoice document number
v5 <- sapply(getNodeSet(xmlParse(xmlfile), "/REPORT/*"), xmlAttrs)
invoicenumber <- sapply(v5, function(x) ifelse("document_id" %in% names(x), x["document_id"], NA))[1]
rm(v5)
documentidnumber <- invoicenumber

doc <- read_xml(xmlfile)

nodes1 <- xml_find_all(doc, xpath = "//REPORT_HEADER")
df1 <- bind_rows(lapply(nodes1, xml_attrs))
df1$publication_date <- as.Date(df1$publication_date, format = "%Y-%m-%d") %>% format("%d/%m/%Y") %>% as.Date(format = "%d/%m/%Y")
df1$due_date <- as.Date(df1$due_date, format = "%Y-%m-%d") %>% format("%d/%m/%Y") %>% as.Date(format = "%d/%m/%Y")

nodes2 <- xml_find_all(doc, xpath = "//CONTACT")
df2 <- bind_rows(lapply(nodes2, xml_attrs))

nodes3 <- xml_find_all(doc, xpath = "//REPORT_SUMMARY")
df3 <- bind_rows(lapply(nodes3, xml_attrs))

nodes4 <- xml_find_all(doc, xpath="//REPORT_DETAIL/*")
df4 <- bind_rows(lapply(nodes4, xml_attrs))
df4 <- rename(.data = df4, 'market2' = 'market', 'interest3' = 'interest')
df4$bp_start_date <- as.Date(df4$bp_start_date, format = "%Y-%m-%d") %>% format("%d/%m/%Y") %>% as.Date(format = "%d/%m/%Y")
df4$bp_end_date <- as.Date(df4$bp_end_date, format = "%Y-%m-%d") %>% format("%d/%m/%Y") %>% as.Date(format = "%d/%m/%Y")

# ============================================================== sales and purchases section ============================================================== #
# Extract attributes from REPORT_DETAIL nodes
nodes_report_detail <- xml_find_all(doc, xpath = "//REPORT_DETAIL/*")
df_report_detail <- bind_rows(lapply(nodes_report_detail, xml_attrs))

# Access the Sales and Purchases sections in REPORT_DETAIL
details <- xml_find_all(doc, "//REPORT_DETAIL/DETAIL")

# Create an empty data frame to store the results
result_df <- data.frame(
  s_total4 = character(),
  s_local5 = character(),
  s_eu6 = character(),
  s_neu7 = character(),
  s_total_prev = character(),
  s_local_prev = character(),
  s_eu_prev = character(),
  s_neu_prev = character(),
  p_total8 = character(),
  p_local9 = character(),
  p_eu10 = character(),
  p_neu11 = character(),
  p_total_prev = character(),
  p_local_prev = character(),
  p_eu_prev = character(),
  p_neu_prev = character(),
  stringsAsFactors = FALSE
)

# Loop through each DETAIL section
for (detail in details) {
  # Access the SALES section
  sales <- xml_find_first(detail, ".//SALES")
  s_total4 <- xml_attr(sales, "s_total")
  s_local5 <- xml_attr(sales, "s_local")
  s_eu6 <- xml_attr(sales, "s_eu")
  s_neu7 <- xml_attr(sales, "s_neu")
  s_total_prev <- xml_attr(sales, "s_total_prev")
  s_local_prev <- xml_attr(sales, "s_local_prev")
  s_eu_prev <- xml_attr(sales, "s_eu_prev")
  s_neu_prev <- xml_attr(sales, "s_neu_prev")
  
  # Access the PURCHASES section
  purchases <- xml_find_first(detail, ".//PURCHASES")
  p_total8 <- xml_attr(purchases, "p_total")
  p_local9 <- xml_attr(purchases, "p_local")
  p_eu10 <- xml_attr(purchases, "p_eu")
  p_neu11 <- xml_attr(purchases, "p_neu")
  p_total_prev <- xml_attr(purchases, "p_total_prev")
  p_local_prev <- xml_attr(purchases, "p_local_prev")
  p_eu_prev <- xml_attr(purchases, "p_eu_prev")
  p_neu_prev <- xml_attr(purchases, "p_neu_prev")
  
  # Append the results to the data frame
  result_df <- rbind(result_df, c(s_total4, s_local5, s_eu6, s_neu7, s_total_prev, s_local_prev, s_eu_prev, s_neu_prev, p_total8, p_local9, p_eu10, p_neu11, p_total_prev, p_local_prev, p_eu_prev, p_neu_prev))
}

# Set column names
colnames(result_df) <- c('s_total4', 's_local5', 's_eu6', 's_neu7', 's_total_prev', 's_local_prev', 's_eu_prev', 's_neu_prev', 'p_total8', 'p_local9', 'p_eu10', 'p_neu11', 'p_total_prev', 'p_local_prev', 'p_eu_prev', 'p_neu_prev')
# ============================================================ sales and purchases section end ============================================================ #

nodes5 <- xml_find_all(doc, xpath = "//REPORT_TRACKING/*")
df5 <- bind_rows(lapply(nodes5, xml_attrs))
df5$statement_date <- as.Date(df5$statement_date, format = "%Y-%m-%d") %>% format("%d/%m/%Y") %>% as.Date(format = "%d/%m/%Y")
colnames(df5) <- c("statement_date", "run_type12", "market13", "charge_name14", "charge_amount", "statement_id")

# offset df5 by 56 rows
df5 <- insertRows(df = df5, r = 1:56)

nodes6 <- xml_find_all(doc, xpath = "//VAT_INFORMATION/STANDARD_INFORMATION/*")
df6 <- bind_rows(lapply(nodes6, xml_attrs))

# repeat certain lines
max_row_count <- max(c(nrow(df1), nrow(df2), nrow(df3), nrow(df4), nrow(df5), nrow(df6)))
df1 <- df1[rep(1:nrow(df1), each = max_row_count), ]
df2 <- df2[rep(1:nrow(df2), each = max_row_count), ]
df3 <- df3[rep(1:nrow(df3), each = max_row_count), ]

df <- cbind.na(df1, df2, df3, df4, result_df, df5, df6)

receiveddate2 <- as.Date(receiveddate, format = "%Y%m%d") %>% format("%d-%m-%Y")

writexl::write_xlsx(df, paste0("C:/Users/", Sys.getenv("USERNAME"),"/Downloads/MO Document ", invoicenumber, " for ", PTunit, " received ", receiveddate2, ".xlsx"))

inputfiles <- list.files(paste0("C:/Users/", Sys.getenv("USERNAME"), "/Downloads"), full.names = TRUE)
inputfiles <- inputfiles[grepl(x = inputfiles, pattern = receiveddate2)]
documentdata <- read_excel(path = inputfiles, sheet = 1)

firstdayd4 <- documentdata %>% filter(run_type == "INIT" & market2 == "MO")
firstdayd4 <- firstdayd4$bp_start_date %>% unique() %>% as.Date(format = "%Y-%m-%d") %>% format("%Y%m%d")

firstdaym4 <- documentdata %>% filter(run_type == "M4" & market2 == "MO")
firstdaym4 <- firstdaym4$bp_start_date %>% unique() %>% as.Date(format = "%Y-%m-%d") %>% format("%Y%m%d")

firstdaym13 <- documentdata %>% filter(run_type == "M13" & market2 == "MO")
firstdaym13 <- firstdaym13$bp_start_date %>% unique() %>% as.Date(format = "%Y-%m-%d") %>% format("%Y%m%d")

firstdayfmoc <- firstdayd4

```

```{r}
##################################################################################################################################################################################################
################################################################################ D+4 settlement section ##########################################################################################
##################################################################################################################################################################################################

# DEFINE VARIABLES
startdate <- documentdata %>%  filter(market2 == "MO" & run_type == "INIT")
startdate <- startdate$bp_start_date %>% unique() %>% as.Date(format = "%Y-%m-%d")
month <- format(startdate, "%b")
month2 <- format(startdate, "%B") %>%  substr(start = 1, stop = 4)
month.as.number <- lubridate::month(startdate)
if (length(month.as.number) == 1) {
  month.as.number <- paste0("0", month.as.number)
}
year <- substring(text = firstday, first = 1, last = 4)
yeard4 <- year
settype <- "D+4"
settype2 <- "D+4 Initial"
settype3 <- "INIT"
settype4 <- "D4"
mm <- 20

# Get MO Doc
inputfiles <- list.files(path = paste0("C:/Users/", Sys.getenv("USERNAME"),"/Downloads/"), full.names = TRUE)
inputfiles <- inputfiles[grepl(pattern = "\\.xlsx$", x = inputfiles)]
inputfiles <- inputfiles[grepl(pattern = PTunit, x = inputfiles)]
inputfiles <- inputfiles[grepl(pattern = "MO", x = inputfiles)]

# Get output file
outputfilename <- paste0(year, " ", month.as.number, ". PT_5000057 SEMO ", month, " ", substr(year, 3,4), " ", settype, " CAPACITY Shadow Settlement - ", initials, ".xlsx")
outputfile <- paste0(accdrive, ":/GeneralAccounts/Settlement/", PTunit, " SEMO Shadow Settlement/Capacity/", settype2, "/", outputfilename)

# Get Workbook Object
mywb <- loadWorkbook(file = outputfile)
openxlsx::writeDataTable(mywb, "MO Summary", as.data.frame(documentdata), 1, 1) # error in file even without this so must be an issue with importing as workbook. 
saveWorkbook(mywb, outputfile, TRUE)

```

